- package.json
- pnpm-lock.yaml
- src/components/ui/Navbar.tsx
- src/components/ui/alert-dialog.tsx
- src/features/wallet/hooks/useCreateCash.ts
- src/features/wallet/hooks/useUpdateCash.ts
##
Create dialog foe reset balance
> Wp 144 reset alert dialog

- src/app/page.tsx
- src/components/ui/header.tsx
##
update header and home page layout and text styles
> Wp 50 update homepage style

- src/features/trading/components/OrderForm.tsx
##
update price input blur handler to trigger market price selection
> fix: update price input blur handler to trigger market price selection

- src/app/api/auth/[...nextauth]/route.ts
- src/features/auth/containers/SignInContainer.tsx
> refactor: improve code structure and readability in SignInContainer

- src/app/main/trading/layout.tsx
- src/components/ui/combobox.tsx
- src/features/trading/components/Chart.tsx
- src/features/trading/components/OrderForm.tsx
- src/features/trading/containers/BuyOrderContainer.tsx
- src/features/trading/containers/SellOrderContainer.tsx
- src/features/trading/contexts/CoinContext.tsx
- src/features/trading/hooks/useMarketPrice.tsx
##
- แก้ที่ input price และ input amount ให้ใส่ทศนิยมได้
- แก้ให้ราคาของแต่ละเหรียญขึ้นแบบ realtime
> Wp 61 use candlestick chart to support decision

- src/app/globals.css
- src/app/main/trading/page.tsx
- src/components/ui/combobox.tsx
- src/features/trading/components/Chart.tsx
> style: fix size of chart

- src/app/api/history/route.ts
- src/app/test/page.tsx
- src/components/ui/PaginationFooter.tsx
- src/features/assets/components/AssetCard.tsx
- src/features/assets/components/HoldingAssetsTable.tsx
- src/features/open-order/components/HistoryApiPreview.tsx
- src/features/open-order/components/HistoryCard.tsx
- src/features/open-order/components/HistoryListPreview.tsx
- src/features/open-order/components/OrderBookWidget.tsx
- src/features/open-order/components/OrderTableContainer.tsx
- src/features/open-order/components/TradeHistoryContainer.tsx
- src/features/open-order/hooks/useGetTradeHistory.ts
- src/features/open-order/types/history.ts
> Wp 111 history

- src/features/assets/components/AssetCard.tsx
- src/features/assets/hooks/useGetAllAssets.ts
- src/features/open-order/components/HistoryListPreview.tsx
- src/features/open-order/components/OpenOrdersList.tsx
- src/features/open-order/components/OrderCard.tsx
- src/features/open-order/components/TradeHistoryContainer.tsx
- src/features/open-order/hooks/useGetTradeHistory.ts
- src/features/trading/containers/AssetCard.tsx
- src/features/trading/containers/OpenOrderContainerAPI.tsx
- src/features/trading/utils/symbolPrecision.ts
##
[Improve: implement Ticker > Tick/Step to improve math.decimal](https://github.com/ss-house-dev/Whalarora-web-frontend/commit/a56f5b648951f93c59a970c1df1aeb2b82af35a3)
fix: pagination loading defect (loading pagination while rendering
> Wp 77 order book

- src/features/open-order/components/HistoryCard.tsx
- src/features/open-order/components/HistoryListPreview.tsx
- src/features/open-order/components/OpenOrdersList.tsx
- src/features/open-order/components/TradeHistoryContainer.tsx
- src/features/open-order/containers/OpenOrdersContainer.tsx
- src/features/open-order/hooks/useGetTradeHistory.ts
- src/features/open-order/types/history.ts
- src/features/trading/containers/OpenOrderContainerAPI.tsx
- src/features/trading/utils/dateFormat.ts
##
Fix: HistoryCard layout due to new design and month-alphabet new format
Fix: display OrderID depends on BUY/SELL side and CLOSE status
> Refine HistoryCard and display format

- src/app/globals.css
- src/components/ui/close-order-box.tsx
- src/features/open-order/components/OrderCard.tsx
##
- fix: close-order popup text and layout
- fix: fix scroll bar
> close-order popup text and layout  and fix scroll bar

- src/components/ui/select-coin.tsx
- src/features/trading/components/Chart.tsx
##
- ทำให้ราคาบน chart กับราคาที่กล่อง buy sell ตรงกัน
- ปรับสไตล์ของ chart
- ปรับวันเวลาของ chart
- ปรับ timezone
- ปรับ comma ราคาบน chart
- ปรับ timeframe
> Wp 289 sync chart price

- .hintrc
- src/components/Navbar.tsx
- src/components/Sidebar.tsx
- src/features/wallet/hooks/useNavbar.ts
##
Responsive
- navbar
- sitebar
New design
- navbar
--- desktop view ---
--- Mobile view ---
> Wp 350 navbar

- src/components/FormItemInput.tsx
- src/features/auth/components/SignInForm.tsx
> add: responsive login page

- src/features/open-order/containers/OrderBookLiveContainer.tsx
- src/features/trading/containers/BuyOrderContainer.tsx
- src/features/trading/containers/OrderContainer.tsx
- src/features/trading/containers/SellOrderContainer.tsx
- src/features/trading/contexts/CoinContext.tsx
##
- เชื่อม tab order book เพื่อให้ set เป็นกล่อง Buy/Sell
-
> Wp 296 order book sync

- src/app/page.tsx
- src/components/Sidebar.tsx
- src/components/header.tsx
##
Responsive
- hero section
- Navbar of hero section
New design
- hero section
- Navbar of hero section
> Wp 362 herosection

- src/app/globals.css
- src/app/main/my-assets/layout.tsx
- src/app/main/trading/layout.tsx
- src/app/main/trading/page.tsx
- src/components/Navbar.tsx
- src/components/combobox.tsx
- src/features/open-order/components/OrderBookWidget.tsx
- src/features/open-order/containers/OrderBookLiveContainer.tsx
- src/features/trading/components/Chart.tsx
- src/features/trading/components/OrderForm.tsx
##
- ทำ responsive หน้า trading : chart, combobox, buy/sell box
> Wp 342 trading page res

- src/components/Sidebar.tsx
- src/components/header.tsx
- src/features/assets/components/AssetCard.tsx
- src/features/assets/components/HoldingAssetsSection.tsx
- src/features/assets/components/HoldingAssetsTable.tsx
- src/features/assets/hooks/useHoldingDesktopBreakpoint.ts
- src/features/open-order/components/OrderBookWidget.tsx
- src/features/open-order/containers/OrderBookLiveContainer.tsx
- src/features/open-order/hooks/useOrderBookStream.ts
- src/features/trading/components/Chart.tsx
- src/features/welcome/components/Welcome.tsx
- src/hooks/use-mobile.ts
##
Responsive trigger/toggle breakpoint for: Holding Assets, Open Order
Implementation: Tick/Step size for OrderBook
> Fix responsive

- src/features/open-order/components/OrderCard.tsx
> Fix: order-card layout for 4-letter symbol type

- src/features/trading/containers/BuyOrderContainer.tsx
- src/features/trading/containers/SellOrderContainer.tsx
##
- แก้การคำนวณเมื่อกรอกที่กล่อง buy/sell
> Fix buy sell box

- src/app/page.tsx
- src/components/header.tsx
##
- update Navbar and responsive
- fix: bug double page
- redesign herosection Navbar
> Wp 359 navbar

- src/app/main/my-assets/page.tsx
- src/app/page.tsx
- src/components/combobox.tsx
- src/features/assets-value/components/TotalAssetsValueCard.tsx
- src/features/assets-value/containers/TotalAssetsValueContainer.tsx
- src/features/assets/components/AssetCard.tsx
- src/features/assets/components/HoldingAssetsTable.tsx
- src/features/assets/containers/HoldingAssetsContainer.tsx
- src/features/assets/hooks/useHoldingDesktopBreakpoint.ts
- src/features/assets/utils/coinMetadata.ts
- src/features/trading/hooks/useMarketPrice.tsx
- src/hooks/use-mobile.ts
##
- ทำ component My assets value
- คำนวณ Total Asset Value (USDT), Total Cost (USDT), Unrealized PnL (USDT)
> Wp 400 display calculation result
